version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  test:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
      - store_test_results:
          path: test-results
workflows:
  version: 2
  periodic:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test