version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: yarn
      - run: jest --ci --runInBand --reporters=default --reporters=jest-junit
      - tore_test_results:
          path: ./reports/
workflows:
  version: 2
  periodic:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
