version: 2.1
orbs:
  node: circleci/node@5.0.3
workflows:
  version: 2
  periodic:
    jobs:
      - node/test:
          test-results-for: mocha
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
