version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
      - store_test_results:
          path: test-results
workflows:
  version: 2
  periodic:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test